x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  app:
    build:
      context: ../../src/aspnetapp
      args:
        - DOTNET_VERSION=${DOTNET_VERSION:-8.0}
    container_name: app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - OTEL_SERVICE_NAME=aspnetapp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      #- OTEL_LOG_LEVEL=debug
    ports:
      - "5000:5000"
    depends_on:
      - jaeger
    logging: *logging
  client:
    image: curlimages/curl:${CURL_VERSION:-latest}
    container_name: client
    command:
      [
        "sh",
        "-c",
        "while true; do curl -H 'X-Trace-ID: $${ID}' -sL http://app:5000/api/Sleep?milliseconds=$${RANDOM};echo; done"
      ]
    environment:
      - ID=${ID:-}
      - RANDOM=${RANDOM:-}
    depends_on:
      app:
        condition: service_started
    logging: *logging
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    container_name: jaeger
    command:
      - "--memory.max-traces=5000"
    ports:
      - "16686:16686" # Jaeger Web UI
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      #- "4317:4317" # Jaeger Collector
      #- "4318:4318" # Jaeger Collector HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    deploy:
      resources:
        limits:
          memory: 400M
    logging: *logging
