global:
  scrape_interval:     5s
  evaluation_interval: 15s

scrape_configs:
  #- job_name: 'app'
  #  scrape_interval: 3s
  #  static_configs:
  #    - targets: [ 'app:5000' ]
  - job_name: aggregated-trace-metrics
    static_configs:
      - targets: ['otel_collector:8889']
