---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: acradtrdemo.azurecr.io/demo/my-app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  selector:
    app: demo
  ports:
   - protocol: "TCP"
     port: 8080
     targetPort: 8080
  type: ClusterIP # LoadBalancer
---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "demo"
spec:
  #tls:
  #  hosts:
  #    - "demo.adtr"
  #secretName: keyvault-demo-adtr
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - host: "demo.adtr"
      http:
        paths:
        - path: "/"
          pathType: "Prefix"
          backend:
            service:
              name: "demo"
              port:
                number: 8080
