services:
  lb:
    build:
      context: .
      args:
        APP_VERSION: 0.0.0-beta
        HOSTNAMES: bar.test.com,baz.test.com
    container_name: lb
    healthcheck:
      test: ["CMD-SHELL", "curl -sf -o /dev/null localhost/health || exit 1"]
      interval: "5s"
    ports:
      - 8080:80

  test-client:
    image: curlimages/curl
    container_name: test-client
    command: |
      sh -c "curl -sL http://lb/health"
    depends_on:
      - lb
