receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
  zipkin:

exporters:
  debug:
    # verbosity: detailed
  prometheus:
    endpoint: "${env:PROMETHEUS_ENDPOINT}"
  logging:
    verbosity: detailed
  #zipkin:
  #  endpoint: "${env:ZIPKIN_ENDPOINT}"
  #  format: proto
  otlp:
    endpoint: "${env:JAEGER_ENDPOINT}"
    #endpoint: "otel-collector:4317"
    tls:
      insecure: true
  loki:
    endpoint: "${env:LOKI_ENDPOINT}"
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers:
        - otlp
        #- zipkin
      processors: [batch]
      exporters:
        - debug
        - otlp
    metrics:
      receivers:
        - otlp
      processors: [batch]
      exporters:
        - debug
        - prometheus
    logs:
      receivers:
        - otlp
      processors: [batch]
      exporters:
        - logging
        - loki
