receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
  zipkin:

exporters:
  debug:
    # verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"
  logging:
    verbosity: detailed
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto
  otlp:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true
  #loki:
  #  endpoint: "http://loki:3100/loki/api/v1/push"
  #  tls:
  #    insecure: true

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  pipelines:
    traces:
      receivers:
        - otlp
        - zipkin
      processors: [batch]
      exporters:
        - debug
        - otlp
    metrics:
      receivers:
        - otlp
      processors: [batch]
      exporters:
        - debug
        - prometheus
    logs:
      receivers:
        - otlp
      processors: [batch]
      exporters:
        - logging
        #- loki
  extensions:
    - zpages
    - health_check
