x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  app:
    build:
      context: ./aspnetapp
    container_name: app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      # automatic instrumentation for .NET (beta)
      - OTEL_SERVICE_NAME=aspnetapp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_LOG_LEVEL=debug
    ports:
      - "5000:5000"
    depends_on:
      - jaeger
    logging: *logging

  traffic-generator:
    image: curlimages/curl:${CURL_VERSION:-latest}
    container_name: traffic-generator
    command:
      [
        "sh",
        "-c",
        "while true; do curl -sL http://app:5000/rolldice; echo; sleep 3; done"
      ]
    depends_on:
      app:
        condition: service_started
    logging: *logging

  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    container_name: jaeger
    command:
      - "--memory.max-traces=5000"
    ports:
      - "16686:16686" # Jaeger Web UI
      - "4317:4317" # Jaeger Collector
      - "4318:4318" # Jaeger Collector HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    deploy:
      resources:
        limits:
          memory: 400M
    logging: *logging