services:
  # installs OpenTelemetry .NET Automatic Instrumentation
  app:
    build:
      context: ./aspnetapp
    container_name: app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # Enable OpenTelemetry .NET Automatic Instrumentation
      - OTEL_SERVICE_NAME="aspnetapp"
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - 8080:8080
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:0.88.0
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 8888:8888 # Prometheus metrics exposed by the Collector (scrape endpoint)
      - 4317:4317 # OpenTelemetry gRPC receiver
      - 55678:55678 #
    environment:
      - JAEGER_ENDPOINT="jaeger:4317"
      - LOKI_ENDPOINT="http://loki:3100/loki/api/v1/push"
    depends_on:
      - jaeger
      - prometheus
      - loki

  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  jaeger:
    image: jaegertracing/all-in-one:1.50.0
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger Web UI

  loki:
    image: grafana/loki:2.7.4
    container_name: loki
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:9.4.3
    container_name: grafana
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    ports:
      - "3000:3000"
