name: .NET
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '8.x' # The .NET SDK version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Unit test
        run: dotnet test --no-restore --verbosity normal
